/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.SocialNetwork;
import modelo.ValidationResponse;
import modelo.Validator;

/**
 *
 * @author Benjamin Parra
 */
public class PanelDeRegistro extends javax.swing.JFrame {
    SocialNetwork snRegistro;
    Validator validator = new Validator();
    ValidationResponse validationResponse = new ValidationResponse();
    /**
     * Creates new form PanelDeRegistro
     * @param sn
     */
    public PanelDeRegistro(SocialNetwork sn) {
        initComponents();
        this.snRegistro = sn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreUser = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        lblRegistro = new javax.swing.JLabel();
        lblIndicacion = new javax.swing.JLabel();
        textNombreUsuario = new javax.swing.JTextField();
        textPass = new javax.swing.JPasswordField();
        btnOk = new javax.swing.JButton();
        btnBackMain = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblNombreUser.setText("Nombre de usuario");

        lblPass.setText("Contraseña");

        lblRegistro.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblRegistro.setText("Registro de Usuario");

        lblIndicacion.setText("Por favor ingrese el nombre y contraseña del usuario a registrar");

        btnOk.setText("OK");
        btnOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOkMouseClicked(evt);
            }
        });

        btnBackMain.setText("Volver atrás");
        btnBackMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackMainActionPerformed(evt);
            }
        });

        btnAyuda.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnAyuda.setText("Ayuda");
        btnAyuda.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblNombreUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnOk)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnBackMain))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(textNombreUsuario)
                                        .addComponent(textPass, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))))
                            .addComponent(lblIndicacion))))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAyuda)
                .addGap(173, 173, 173))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lblIndicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreUser)
                    .addComponent(textNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass)
                    .addComponent(textPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBackMain)
                    .addComponent(btnOk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAyuda)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkMouseClicked
        String nombreUsuario= textNombreUsuario.getText();
        String password = textPass.getText();
        String[] usuarioString = {nombreUsuario,password};
        validationResponse = validator.validadorUsuario(usuarioString , snRegistro);
        if (validationResponse.isEsValido()) {
            snRegistro.registerUser(usuarioString, snRegistro.getFecha());
            Mensajes nm = new Mensajes("El usuario se ha registrado exitosamente",this,true,snRegistro);
            nm.setLocationRelativeTo(null);
            nm.setVisible(true);
            //textNombreUsuario.setText("");
            textPass.setText("");
        }else if (!validationResponse.isEsValido()) {
            //this.dispose();
            Mensajes nm = new Mensajes(validationResponse.getMensaje(),this,true,snRegistro);
            nm.setLocationRelativeTo(null);
            nm.setVisible(true);
            textNombreUsuario.setText("");
            textPass.setText("");
            
        }
        
        
    }//GEN-LAST:event_btnOkMouseClicked

    private void btnBackMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackMainActionPerformed
        // TODO add your handling code here:
        Menu_Bienvenida mb = new Menu_Bienvenida(snRegistro);
        mb.setLocationRelativeTo(this);
        this.dispose();
        mb.setVisible(true);
    }//GEN-LAST:event_btnBackMainActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        // TODO add your handling code here:
        Mensajes nm = new Mensajes("Para registrar un usuario\n\n A) El nombre del usuario debe contener 6 caracteres (minimo 4 de ellos deben ser letras) y solo caracteres alfanumericos \n\n B) La contrasena debe tener un largo de 6 caracteres, debe contener al menos 3 numeros y no puede contener espacios \n\n C) La contrasena no puede ser igual que el nombre de usuario\n\n",this,true,snRegistro);
        nm.setLocationRelativeTo(null);
        nm.setVisible(true);
    }//GEN-LAST:event_btnAyudaActionPerformed

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelDeRegistro(snRegistro).setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnBackMain;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel lblIndicacion;
    private javax.swing.JLabel lblNombreUser;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblRegistro;
    private javax.swing.JTextField textNombreUsuario;
    private javax.swing.JPasswordField textPass;
    // End of variables declaration//GEN-END:variables
}
