/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import modelo.SocialNetwork;
import modelo.ValidationResponse;
import modelo.Validator;

/**
 * Esta ventana es para el inicio de sesión
 * @author Benjamin Parra
 */
public class PanelDeInicio extends javax.swing.JFrame {
    SocialNetwork snInicio;
    private ImageIcon imagen;
    private Icon icono;
    ValidationResponse validationResponse = new ValidationResponse();
    Validator validator = new Validator();
    /**
     * Creates new form PanelDeInicio
     * @param sn
     */
    public PanelDeInicio(SocialNetwork sn) {
        initComponents();
        this.snInicio = sn;
        pintarImagen(lblLogoLogin, "src/main/java/vista/logoLogin.png");
    }
    /**
     * Metodo obtenido de videoTutoriales que para montar imagenes
     * en Jlabel
     * @param lbl
     * @param ruta 
     */
    private void pintarImagen(JLabel lbl, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(
                        lbl.getWidth(), 
                        lbl.getHeight(), 
                        Image.SCALE_DEFAULT
                )
        );
        lbl.setIcon(this.icono);
        this.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInicio = new javax.swing.JLabel();
        lblNombreUser = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        lblIndicacion = new javax.swing.JLabel();
        textNombreUsuario = new javax.swing.JTextField();
        textPass = new javax.swing.JPasswordField();
        btnOk = new javax.swing.JButton();
        btnBackMain = new javax.swing.JButton();
        lblLogoLogin = new javax.swing.JLabel();
        btnAyuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblInicio.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblInicio.setText("Inicio de sesión");

        lblNombreUser.setText("Nombre de Usuario");

        lblPass.setText("Contraseña");

        lblIndicacion.setText("Por favor ingrese nombre y contraseña");

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnBackMain.setText("Volver atrás");
        btnBackMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackMainActionPerformed(evt);
            }
        });

        btnAyuda.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnAyuda.setText("Ayuda");
        btnAyuda.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblLogoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInicio))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIndicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPass)
                                    .addComponent(lblNombreUser))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(textNombreUsuario)
                                        .addComponent(textPass, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnOk)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBackMain)))))))
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAyuda)
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lblLogoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblInicio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(lblIndicacion)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreUser)
                    .addComponent(textNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass)
                    .addComponent(textPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnBackMain))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAyuda)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        String nombreUsuario = textNombreUsuario.getText();
        String password = textPass.getText();
        String[] datosUsuario = {nombreUsuario,password};
        validationResponse = validator.validadorLogin(datosUsuario, snInicio);
        if (validationResponse.isEsValido()) {
            //this.dispose();
            snInicio.login(nombreUsuario);
            Mensajes nm = new Mensajes("El usuario ha iniciado sesión",this,true,snInicio);
            nm.setLocationRelativeTo(null);
            nm.setVisible(true);
            PanelDeSesionIniciada pSI = new PanelDeSesionIniciada(snInicio);
            this.dispose();
            pSI.setLocationRelativeTo(null);
            pSI.setVisible(true);
            textNombreUsuario.setText("");
            textPass.setText("");
        }else if (!validationResponse.isEsValido()) {
            //this.dispose();
            Mensajes nm = new Mensajes(validationResponse.getMensaje(),this,true,snInicio);
            nm.setLocationRelativeTo(null);
            nm.setVisible(true);
            textNombreUsuario.setText("");
            textPass.setText("");
        }
        
        
        
    }//GEN-LAST:event_btnOkActionPerformed
/**
 * Este boton es para retornar al main
 * @param evt 
 */
    private void btnBackMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackMainActionPerformed
        Menu_Bienvenida mb = new Menu_Bienvenida(snInicio);
        mb.setLocationRelativeTo(this);
        this.dispose();
        mb.setVisible(true);
    }//GEN-LAST:event_btnBackMainActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        // TODO add your handling code here:
        Mensajes nm = new Mensajes("Procure ingresar el nombre y contraseña respetando minúsculas, mayúsculas y no agregue espacios en blanco",this,true,snInicio);
        nm.setLocationRelativeTo(null);
        nm.setVisible(true);
    }//GEN-LAST:event_btnAyudaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnBackMain;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel lblIndicacion;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblLogoLogin;
    private javax.swing.JLabel lblNombreUser;
    private javax.swing.JLabel lblPass;
    private javax.swing.JTextField textNombreUsuario;
    private javax.swing.JPasswordField textPass;
    // End of variables declaration//GEN-END:variables
}
