/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.SocialNetwork;
import modelo.ValidationResponse;
import modelo.Validator;

/**
 * Esta ventana es para el inicio de sesión
 * @author Benjamin Parra
 */
public class PanelDeInicio extends javax.swing.JFrame {
    SocialNetwork snInicio;
    /**
     * Creates new form PanelDeInicio
     * @param sn
     */
    public PanelDeInicio(SocialNetwork sn) {
        initComponents();
        this.snInicio = sn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textNombreUsuario = new javax.swing.JTextField();
        textPass = new javax.swing.JPasswordField();
        btnOk = new javax.swing.JButton();
        btnBackMain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel1.setText("Inicio de sesión");

        jLabel2.setText("Nombre de Usuario");

        jLabel3.setText("Contraseña");

        jLabel4.setText("Por favor ingrese nombre y contraseña");

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnBackMain.setText("Volver atrás");
        btnBackMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBackMain)
                                .addGap(42, 42, 42)
                                .addComponent(btnOk))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textNombreUsuario)
                                .addComponent(textPass, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnBackMain))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        
        Validator validator = new Validator();
        String nombreUsuario = textNombreUsuario.getText();
        String password = textPass.getText();
        String[] datosUsuario = {nombreUsuario,password};
        ValidationResponse validationResponse = new ValidationResponse();
        validationResponse = validator.validadorLogin(datosUsuario, snInicio);
        
        /*
        PanelDeSesionIniciada pSI = new PanelDeSesionIniciada(snInicio);
        this.dispose();
        pSI.setLocationRelativeTo(null);
        pSI.setVisible(true);*/
        
        if (validationResponse.isEsValido()) {
            //this.dispose();
            snInicio.login(nombreUsuario);
            Mensajes nm = new Mensajes("El usuario ha iniciado sesión",this,true,snInicio);
            nm.setLocationRelativeTo(null);
            nm.setVisible(true);
            PanelDeSesionIniciada pSI = new PanelDeSesionIniciada(snInicio);
            this.dispose();
            pSI.setLocationRelativeTo(null);
            pSI.setVisible(true);
            textNombreUsuario.setText("");
            textPass.setText("");
            
        }else if (!validationResponse.isEsValido()) {
            //this.dispose();
            Mensajes nm = new Mensajes(validationResponse.getMensaje(),this,true,snInicio);
            nm.setLocationRelativeTo(null);
            nm.setVisible(true);
            textNombreUsuario.setText("");
            textPass.setText("");
            
        }
        
        
        
    }//GEN-LAST:event_btnOkActionPerformed
/**
 * Este boton es para retornar al main
 * @param evt 
 */
    private void btnBackMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackMainActionPerformed
        // TODO add your handling code here:
        Menu_Bienvenida mb = new Menu_Bienvenida(snInicio);
        mb.setLocationRelativeTo(this);
        this.dispose();
        
        mb.setVisible(true);
    }//GEN-LAST:event_btnBackMainActionPerformed

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelDeInicio().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackMain;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField textNombreUsuario;
    private javax.swing.JPasswordField textPass;
    // End of variables declaration//GEN-END:variables
}
