/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import modelo.SocialNetwork;
import modelo.ValidationResponse;
import modelo.Validator;

/**
 *
 * @author Benjamin Parra
 */
public class PanelPost extends javax.swing.JFrame {
    SocialNetwork snPost;
    private ImageIcon imagen;
    private Icon icono;

    /**
     * Creates new form PanelPost
     * @param sn
     */
    public PanelPost(SocialNetwork sn) {
        initComponents();
        this.snPost = sn;
        mostrar();
        pintarImagen(lblSeguirLogo, "src/main/java/vista/logoPost.png");
    }
    
    private void pintarImagen(JLabel lbl, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(
                        lbl.getWidth(), 
                        lbl.getHeight(), 
                        Image.SCALE_DEFAULT
                )
        );
        lbl.setIcon(this.icono);
        this.repaint();
        
    }
    /**
     * Metodo que muestra la tabla de amigos
     */
    public void mostrar(){
        DefaultTableModel modelo = (DefaultTableModel)tableAmigos.getModel();
        for (int i = 0; i < snPost.getUserOnline().getAmigos().size(); i++) {
            modelo.addRow(new Object[]{snPost.getUserOnline().getAmigos().get(i).getNombreUsuario(),false});
        }
    }
    
    /**
     * Metodo que entrega el string representativo
     * del tipo de los botones 
     * @return 
     */
    public String getBtnSelected(){
       String retorno = "";
        if (btnAudio.isSelected()) {
            retorno = ".audio";
        }else if(btnPhoto.isSelected()){
            retorno = ".photo";
        }else if(btnText.isSelected()){
            retorno = ".text";
        }else if(btnVideo.isSelected()){
            retorno = ".video";
        }else if(btnUrl.isSelected()){
            retorno = ".url";
        }
       
       return retorno;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAmigos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textContenido = new javax.swing.JTextPane();
        btnText = new javax.swing.JRadioButton();
        btnVideo = new javax.swing.JRadioButton();
        btnUrl = new javax.swing.JRadioButton();
        btnPhoto = new javax.swing.JRadioButton();
        btnAudio = new javax.swing.JRadioButton();
        btnPost = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSeguirLogo = new javax.swing.JLabel();
        btnAyuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel1.setText("Crear publicación");

        tableAmigos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NombreUsuario", "Selección"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableAmigos);
        if (tableAmigos.getColumnModel().getColumnCount() > 0) {
            tableAmigos.getColumnModel().getColumn(1).setMinWidth(10);
            tableAmigos.getColumnModel().getColumn(1).setMaxWidth(100);
        }

        jLabel2.setText("Ingrese el contenido de la publicación");

        jScrollPane2.setViewportView(textContenido);

        buttonGroup1.add(btnText);
        btnText.setText(".text");
        btnText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTextActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnVideo);
        btnVideo.setText(".video");

        buttonGroup1.add(btnUrl);
        btnUrl.setText(".url");

        buttonGroup1.add(btnPhoto);
        btnPhoto.setText(".photo");

        buttonGroup1.add(btnAudio);
        btnAudio.setText(".audio");

        btnPost.setText("Post");
        btnPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostActionPerformed(evt);
            }
        });

        btnBack.setText("Volver atrás");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo");

        jLabel4.setText("Amigos");

        lblSeguirLogo.setText("jLabel5");
        lblSeguirLogo.setMaximumSize(new java.awt.Dimension(81, 81));

        btnAyuda.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnAyuda.setText("Ayuda");
        btnAyuda.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(btnVideo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnUrl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPhoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAudio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(btnAyuda))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblSeguirLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblSeguirLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVideo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUrl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPhoto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAudio)
                                .addGap(18, 18, 18)
                                .addComponent(btnPost, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAyuda)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        PanelDeSesionIniciada psi = new PanelDeSesionIniciada(snPost);
        psi.setLocationRelativeTo(this);
        this.dispose();
        psi.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostActionPerformed
        ArrayList<String> amigosSeleccionados = new ArrayList();
        DefaultTableModel modelo = (DefaultTableModel)tableAmigos.getModel();
        String amigosComo = "";
        Validator validator = new Validator();
        ValidationResponse validationResponse = new ValidationResponse();
        
        //verifica que las opciones del tipo del texto
        if (!btnAudio.isSelected()&& !btnPhoto.isSelected()&&!btnUrl.isSelected()&&
                !btnVideo.isSelected()&&!btnText.isSelected()) {
            Mensajes mensaje = new Mensajes("ERROR: Seleccione algun tipo de publicación",this,true,snPost);
            mensaje.setLocationRelativeTo(null);
            mensaje.setVisible(true);
            
        }
        if (textContenido.getText().isEmpty()) {
            Mensajes mensajeCn = new Mensajes("ERROR: No deje en blanco el contenido",this,true,snPost);
            mensajeCn.setLocationRelativeTo(null);
            mensajeCn.setVisible(true);
        }else{
            for (int i = 0; i < snPost.getUserOnline().getAmigos().size(); i++) {
                if ("true".equalsIgnoreCase(""+modelo.getValueAt(i, 1))) {
                    amigosSeleccionados.add(snPost.getUserOnline().getAmigos().get(i).getNombreUsuario());
                    //amigosSeleccionados.add((String) modelo.getValueAt(i, 0));
                }
            }
            for (int i = 0; i < amigosSeleccionados.size(); i++) {
                amigosComo = amigosSeleccionados.get(i)+",";
            }
            String[] nuevoString = new String[amigosSeleccionados.size()];
            for (int i = 0; i < amigosSeleccionados.size(); i++) {
                nuevoString[i] = amigosSeleccionados.get(i);
            }
            if (amigosSeleccionados.isEmpty()) {
                String[] contenidoTipo = {textContenido.getText(),getBtnSelected()};
                validationResponse = validator.validadorPostSolo(contenidoTipo, snPost,snPost.getFecha());
                if (!validationResponse.isEsValido()) {
                    Mensajes mensaje = new Mensajes(validationResponse.getMensaje(),this,true,snPost);
                    mensaje.setLocationRelativeTo(null);
                    mensaje.setVisible(true);
                    textContenido.setText("");
                }else{
                    snPost.getUserOnline().post(contenidoTipo[0]+contenidoTipo[1], snPost);
                    Mensajes mensaje = new Mensajes("El usuario "+snPost.getUserOnline().getNombreUsuario()+" realizo la publicacion en su muro",this,true,snPost);
                    mensaje.setLocationRelativeTo(null);
                    mensaje.setVisible(true);
                }
            }else if (!amigosSeleccionados.isEmpty()){
                String[] contenidoTipo = {textContenido.getText(),getBtnSelected()};
                String[] contenidoPost = {contenidoTipo[0]+contenidoTipo[1],amigosComo};
                validationResponse = validator.validadorPost(contenidoPost, snPost);
                if (!validationResponse.isEsValido()) {
                    Mensajes mensaje = new Mensajes(validationResponse.getMensaje(),this,true,snPost);
                    mensaje.setLocationRelativeTo(null);
                    mensaje.setVisible(true);
                }else{
                    snPost.getUserOnline().post(contenidoTipo[0]+contenidoTipo[1], nuevoString, snPost);
                    Mensajes mensaje = new Mensajes(snPost.mensajePostAmigos(nuevoString)+"\n",this,true,snPost);
                    mensaje.setLocationRelativeTo(null);
                    mensaje.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_btnPostActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        // TODO add your handling code here:
        Mensajes nm = new Mensajes("Para realizar una publicación en tu perfil no debes seleccionar a ningún usuario. \n\n Para realizar la publicación a otro/os usuario/usuarios solo debes seleccionarlos.",this,true,snPost);
        nm.setLocationRelativeTo(null);
        nm.setVisible(true);
    }//GEN-LAST:event_btnAyudaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAudio;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnBack;
    private javax.swing.JRadioButton btnPhoto;
    private javax.swing.JButton btnPost;
    private javax.swing.JRadioButton btnText;
    private javax.swing.JRadioButton btnUrl;
    private javax.swing.JRadioButton btnVideo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblSeguirLogo;
    private javax.swing.JTable tableAmigos;
    private javax.swing.JTextPane textContenido;
    // End of variables declaration//GEN-END:variables
}
