/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.SocialNetwork;

/**
 *
 * @author Benjamin Parra
 */
public class PanelDeSesionIniciada extends javax.swing.JFrame {

    /**
     * Creates new form PanelDeSesionIniciada
     */
    public PanelDeSesionIniciada() {
        initComponents();
        textNombreUsuario.setText("Benjamin Parra");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        textNombreUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        radioButtonPost = new javax.swing.JRadioButton();
        radioButtonFollow = new javax.swing.JRadioButton();
        radioButtonShare = new javax.swing.JRadioButton();
        radioButtonVisualize = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        radioButtonLogout = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setText("Sesión Iniciada");

        textNombreUsuario.setBackground(new java.awt.Color(255, 0, 102));
        textNombreUsuario.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N

        jLabel2.setText("Menú de opciones:");

        buttonGroup1.add(radioButtonPost);
        radioButtonPost.setText("Realizar publicación");

        buttonGroup1.add(radioButtonFollow);
        radioButtonFollow.setText("Seguir Usuario");

        buttonGroup1.add(radioButtonShare);
        radioButtonShare.setText("Compartir publicación");

        buttonGroup1.add(radioButtonVisualize);
        radioButtonVisualize.setText("Visualizar RedSocial");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioButtonLogout);
        radioButtonLogout.setText("Cerrar sesión");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioButtonFollow)
                            .addComponent(radioButtonPost)
                            .addComponent(radioButtonShare)
                            .addComponent(radioButtonVisualize)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioButtonLogout))))
                .addContainerGap(398, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(textNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioButtonPost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButtonFollow)
                .addGap(18, 18, 18)
                .addComponent(radioButtonShare)
                .addGap(18, 18, 18)
                .addComponent(radioButtonVisualize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioButtonLogout)
                .addGap(28, 28, 28)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SocialNetwork sn = new SocialNetwork("Facebook","27/12/2021");
        String[] datosUser = {"benjaminParra","benja123"};
        sn.registerUser(datosUser, sn.getFecha());
        if (radioButtonFollow.isSelected()) {
            //se abre ventana follow
        }
        if (radioButtonPost.isSelected()) {
            //se abre ventana follow
        }
        if (radioButtonShare.isSelected()){
            //se abre ventanaShare
        }
        if (radioButtonVisualize.isSelected()) {
            //se abre ventana visualizar
        }
        if (radioButtonLogout.isSelected()) {
            sn.turnOffUser();
            Mensajes mensaje = new Mensajes("Se ha cerrado sesión",this,true);
            mensaje.setLocationRelativeTo(null);
            mensaje.setVisible(true);
            this.dispose();
            Menu_Bienvenida mB = new Menu_Bienvenida();
            mB.setLocationRelativeTo(null);
            mB.setVisible(true);
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelDeSesionIniciada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelDeSesionIniciada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelDeSesionIniciada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelDeSesionIniciada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelDeSesionIniciada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton radioButtonFollow;
    private javax.swing.JRadioButton radioButtonLogout;
    private javax.swing.JRadioButton radioButtonPost;
    private javax.swing.JRadioButton radioButtonShare;
    private javax.swing.JRadioButton radioButtonVisualize;
    private javax.swing.JLabel textNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
